spring:
  application:
    name: Ant

thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true

server:
  port: 8088

openai:
  api-key: ${OPENAI_API_KEY}